name: sadie-production
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python>=3.13
  - pip:
    - biopython>=1.84
    - charset-normalizer>=3.3.0
    - click>=8.1.7
    - et-xmlfile>=1.1.0
    - filetype>=1.2.0
    - idna>=3.6
    - joblib>=1.3.0
    - multidict>=6.0.4
    - numpy>=1.24,<2.0
    - openpyxl>=3.1.0
    - pandas>=1.5,<=2.2
    - psutil>=5.9.0
    - pyarrow>=8.0.0,<17.0.0
    - pydantic>=2.0.0,<3.0.0
    - pyhmmer>=0.10.14
    - python-dateutil>=2.8.2
    - python-levenshtein>=0.25.0
    - pytz>=2024.1
    - pyyaml>=6.0
    - requests>=2.32.0
    - sadie-antibody>=1.1.2
    - scikit-learn>=1.5.0
    - scipy>=1.11.0
    - semantic-version>=2.10.0
    - six>=1.16.0
    - threadpoolctl>=3.1.0
    - typing-extensions>=4.8.0
    - urllib3>=2.0.0
    - yarl>=1.9.0
    - nb-black>=1.0.7
