[build]
command = """
pip3 install -q poetry &&
poetry config virtualenvs.in-project true &&
poetry install -v --with dev &&
mkdocs build
"""
publish = "site"

[build.environment]
PYTHON_VERSION = "3.11"
