"""
This type stub file was generated by pyright.
"""

from typing import Any

from Bio.Align import MultipleSeqAlignment as MultipleSeqAlignment
from Bio.File import as_handle as as_handle
from Bio.SeqIO import AbiIO as AbiIO
from Bio.SeqIO import AceIO as AceIO
from Bio.SeqIO import FastaIO as FastaIO
from Bio.SeqIO import GckIO as GckIO
from Bio.SeqIO import IgIO as IgIO
from Bio.SeqIO import InsdcIO as InsdcIO
from Bio.SeqIO import NibIO as NibIO
from Bio.SeqIO import PdbIO as PdbIO
from Bio.SeqIO import PhdIO as PhdIO
from Bio.SeqIO import PirIO as PirIO
from Bio.SeqIO import QualityIO as QualityIO
from Bio.SeqIO import SeqXmlIO as SeqXmlIO
from Bio.SeqIO import SffIO as SffIO
from Bio.SeqIO import SnapGeneIO as SnapGeneIO
from Bio.SeqIO import SwissIO as SwissIO
from Bio.SeqIO import TabIO as TabIO
from Bio.SeqIO import TwoBitIO as TwoBitIO
from Bio.SeqIO import UniprotIO as UniprotIO
from Bio.SeqIO import XdnaIO as XdnaIO
from Bio.SeqRecord import SeqRecord as SeqRecord

def write(sequences, handle, format) -> None: ...
def parse(handle, format, alphabet: Any | None = ...): ...
def read(handle, format, alphabet: Any | None = ...): ...
def to_dict(sequences, key_function: Any | None = ...): ...
def index(filename, format, alphabet: Any | None = ..., key_function: Any | None = ...): ...
def index_db(
    index_filename,
    filenames: Any | None = ...,
    format: Any | None = ...,
    alphabet: Any | None = ...,
    key_function: Any | None = ...,
): ...
def convert(in_file, in_format, out_file, out_format, molecule_type: Any | None = ...): ...
