name: Coverage Report

on:
  push:
    tags:
      - '*'
    branches: ['main']
  pull_request:
    branches: ['main', 'update_doc', 'development']

jobs:
  coverage:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.13']
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache Poetry dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry
            ~/Library/Caches/pypoetry
            ~/.local/share/pypoetry
            ~/Library/Application Support/pypoetry
          key: ${{ runner.os }}-poetry-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-${{ matrix.python-version }}-
            ${{ runner.os }}-poetry-
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libuv1 ncbi-blast+ build-essential
      - name: Setup build environment
        run: |
          python -m pip install --upgrade pip setuptools wheel
          # Pre-install problematic packages with binary wheels if available
          python -m pip install --prefer-binary numpy scipy scikit-learn pandas
          # Install yarl and multidict (not needed for Ubuntu but keeping for consistency)
          python -m pip install yarl multidict
          # Install poetry
          pip install poetry
      - name: Install dependencies
        run: |
          # Try to install with retries and better error handling
          poetry install --with dev || {
            echo "First attempt failed, trying with verbose output..."
            poetry install --with dev -vvv || {
              echo "Installation failed. Attempting to install without optional dependencies..."
              poetry install --with dev --no-interaction || exit 1
            }
          }
      - name: Test
        run: |
          poetry run coverage run --source=sadie -m pytest tests/unit/
          poetry run coverage html
          poetry run coverage xml
          poetry run coverage report
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: ./coverage
      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          name: codecov-umbrella
          fail_ci_if_error: false
          verbose: true
