name: Coverage Report

on:
  push:
    tags:
      - '*'
    branches: ['main']
  pull_request:
    branches: ['main', 'update_doc', 'development']

jobs:
  coverage:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.13']
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libuv1 ncbi-blast+
      - name: Install dependencies
        run: |
          pip install poetry
          pip install wheel
          poetry install --with dev
      - name: Test
        run: |
          poetry run coverage run --source=sadie -m pytest tests/unit/
          poetry run coverage html
          poetry run coverage xml
          poetry run coverage report
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: ./coverage
      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          name: codecov-umbrella
          fail_ci_if_error: false
          verbose: true
