name: Coverage Report (pytest-cov)

on:
  push:
    tags:
      - '*'
    branches: ['main']
  pull_request:
    branches: ['main', 'update_doc', 'development']

jobs:
  coverage:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.13']
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libuv1 ncbi-blast+
      - name: Install dependencies
        run: |
          pip install poetry
          pip install wheel
          # Install pytest-cov separately
          poetry install --with dev
      - name: Test with pytest-cov
        env:
          # Add debugging for segfaults
          PYTHONFAULTHANDLER: 1
          PYTHONMALLOC: malloc
        run: |
          echo "Running tests with pytest-cov..."
          # Use pytest-cov instead of coverage directly
          poetry run pytest -xsv tests/unit/ \
            --cov=sadie \
            --cov-report=html:coverage/reports/html \
            --cov-report=xml:coverage.xml \
            --cov-report=term \
            --cov-config=pyproject.toml \
            -v || {
              echo "pytest-cov failed. Running tests without coverage..."
              poetry run pytest tests/unit/ -v
              exit 1
            }
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: ./coverage
      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          name: codecov-umbrella
          fail_ci_if_error: false
          verbose: true
