name: Static Type Check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main", "update_doc", "development"]

jobs:
  pyright:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --with dev
      - name: Static Type Check
        run: poetry run pyright
