#!/usr/bin/env python3
"""
Gapping Accuracy Validation Tests
==================================

Compares in-silico gapped sequences generated by GapperService against
the original G3 gapped sequences to quantify accuracy.

This helps validate that the BioPython alignment-based gapping approach
produces sequences that closely match the expected IMGT gapping.

Metrics:
- Exact match rate: Percentage of sequences with identical gapping
- Gap position accuracy: How many gap positions match
- Sequence identity: Overall character-by-character match rate
"""

import logging
from pathlib import Path
from typing import Dict, List, Tuple, Optional
from dataclasses import dataclass
from collections import defaultdict

from Bio import SeqIO

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


@dataclass
class GappingComparison:
    """Results of comparing one sequence's gapping."""
    gene_name: str
    ungapped_length: int
    expected_gapped_length: int
    actual_gapped_length: int
    expected_gap_count: int
    actual_gap_count: int
    exact_match: bool
    gap_position_matches: int
    gap_position_total: int
    character_matches: int
    character_total: int
    
    @property
    def gap_position_accuracy(self) -> float:
        if self.gap_position_total == 0:
            return 1.0
        return self.gap_position_matches / self.gap_position_total
    
    @property
    def character_accuracy(self) -> float:
        if self.character_total == 0:
            return 1.0
        return self.character_matches / self.character_total


def load_fasta_sequences(fasta_path: Path) -> Dict[str, str]:
    """Load sequences from FASTA file into dict."""
    sequences = {}
    for record in SeqIO.parse(fasta_path, "fasta"):
        # Handle gene name extraction
        name = record.id.split("|")[0]
        sequences[name] = str(record.seq).upper()
    return sequences


def compare_gapped_sequences(
    expected: str,
    actual: str
) -> Tuple[bool, int, int, int, int]:
    """
    Compare two gapped sequences.
    
    Returns:
        (exact_match, gap_pos_matches, gap_pos_total, char_matches, char_total)
    """
    # Normalize gap characters
    expected = expected.replace("-", ".")
    actual = actual.replace("-", ".")
    
    exact_match = expected == actual
    
    # Find gap positions in expected
    expected_gap_positions = {i for i, c in enumerate(expected) if c == "."}
    actual_gap_positions = {i for i, c in enumerate(actual) if c == "."}
    
    # Gap position accuracy
    all_gap_positions = expected_gap_positions | actual_gap_positions
    matching_positions = expected_gap_positions & actual_gap_positions
    
    gap_pos_total = len(all_gap_positions)
    gap_pos_matches = len(matching_positions)
    
    # Character-by-character accuracy (pad to same length)
    max_len = max(len(expected), len(actual))
    expected_padded = expected.ljust(max_len, " ")
    actual_padded = actual.ljust(max_len, " ")
    
    char_matches = sum(1 for e, a in zip(expected_padded, actual_padded) if e == a)
    char_total = max_len
    
    return exact_match, gap_pos_matches, gap_pos_total, char_matches, char_total


def validate_species_gapping(
    custom_dir: Path,
    species: str,
    template_dir: Path
) -> Dict[str, List[GappingComparison]]:
    """
    Validate gapping accuracy for a species.
    
    Compares in-silico gapped sequences against G3 original gapped sequences.
    
    Parameters
    ----------
    custom_dir : Path
        Directory containing custom FASTA files
    species : str
        Species name
    template_dir : Path
        IMGT template directory
        
    Returns
    -------
    Dict[str, List[GappingComparison]]
        Results by segment (IGHV, IGKV, etc.)
    """
    import sys
    sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))
    
    from sadie.germlines.builders.gapper import GapperService
    
    species_dir = custom_dir / species
    if not species_dir.exists():
        logger.warning(f"Species directory not found: {species_dir}")
        return {}
    
    results = defaultdict(list)
    
    # Initialize gapper with IMGT templates
    gapper = GapperService(template_dir=template_dir)
    
    # Find all segment files
    for ungapped_file in species_dir.glob("IG*.fasta"):
        if "_gapped" in ungapped_file.name:
            continue
            
        segment_name = ungapped_file.stem  # e.g., "IGHV"
        gapped_file = species_dir / f"{segment_name}_gapped.fasta"
        
        if not gapped_file.exists():
            logger.warning(f"No gapped file for validation: {gapped_file}")
            continue
        
        # Parse segment info
        if len(segment_name) >= 4:
            chain = segment_name[2]  # H, K, or L
            segment = segment_name[3]  # V, D, or J
        else:
            continue
        
        logger.info(f"Validating {species}/{segment_name}...")
        
        # Load sequences
        ungapped_seqs = load_fasta_sequences(ungapped_file)
        expected_gapped_seqs = load_fasta_sequences(gapped_file)
        
        # Compare each sequence
        for gene_name, ungapped_seq in ungapped_seqs.items():
            expected_gapped = expected_gapped_seqs.get(gene_name)
            
            if not expected_gapped:
                logger.debug(f"No expected gapped sequence for {gene_name}")
                continue
            
            # Generate in-silico gapped sequence
            # Use 'human' as template species since that's what we fall back to
            actual_gapped = gapper.gap_sequence(
                sequence=ungapped_seq,
                segment=segment,
                chain=chain,
                gene_name=gene_name,
                species="human"  # Use human templates for comparison
            )
            
            if actual_gapped is None:
                # Gapping failed
                results[segment_name].append(GappingComparison(
                    gene_name=gene_name,
                    ungapped_length=len(ungapped_seq),
                    expected_gapped_length=len(expected_gapped),
                    actual_gapped_length=0,
                    expected_gap_count=expected_gapped.count("."),
                    actual_gap_count=0,
                    exact_match=False,
                    gap_position_matches=0,
                    gap_position_total=expected_gapped.count("."),
                    character_matches=0,
                    character_total=len(expected_gapped)
                ))
                continue
            
            # Compare sequences
            exact_match, gap_pos_matches, gap_pos_total, char_matches, char_total = \
                compare_gapped_sequences(expected_gapped, actual_gapped)
            
            results[segment_name].append(GappingComparison(
                gene_name=gene_name,
                ungapped_length=len(ungapped_seq),
                expected_gapped_length=len(expected_gapped),
                actual_gapped_length=len(actual_gapped),
                expected_gap_count=expected_gapped.count("."),
                actual_gap_count=actual_gapped.count("."),
                exact_match=exact_match,
                gap_position_matches=gap_pos_matches,
                gap_position_total=gap_pos_total,
                character_matches=char_matches,
                character_total=char_total
            ))
    
    return dict(results)


def print_validation_report(
    results: Dict[str, Dict[str, List[GappingComparison]]],
    output_path: Optional[Path] = None
) -> str:
    """Generate and print validation report."""
    lines = []
    lines.append("=" * 80)
    lines.append("GAPPING ACCURACY VALIDATION REPORT")
    lines.append("=" * 80)
    lines.append("")
    
    overall_exact = 0
    overall_total = 0
    overall_gap_pos_matches = 0
    overall_gap_pos_total = 0
    overall_char_matches = 0
    overall_char_total = 0
    
    for species, segments in sorted(results.items()):
        lines.append(f"\n## {species.upper()}")
        lines.append("-" * 40)
        
        for segment, comparisons in sorted(segments.items()):
            exact_matches = sum(1 for c in comparisons if c.exact_match)
            total = len(comparisons)
            
            gap_pos_matches = sum(c.gap_position_matches for c in comparisons)
            gap_pos_total = sum(c.gap_position_total for c in comparisons)
            
            char_matches = sum(c.character_matches for c in comparisons)
            char_total = sum(c.character_total for c in comparisons)
            
            overall_exact += exact_matches
            overall_total += total
            overall_gap_pos_matches += gap_pos_matches
            overall_gap_pos_total += gap_pos_total
            overall_char_matches += char_matches
            overall_char_total += char_total
            
            exact_rate = exact_matches / total * 100 if total > 0 else 0
            gap_acc = gap_pos_matches / gap_pos_total * 100 if gap_pos_total > 0 else 100
            char_acc = char_matches / char_total * 100 if char_total > 0 else 100
            
            lines.append(f"\n### {segment}")
            lines.append(f"  Sequences: {total}")
            lines.append(f"  Exact matches: {exact_matches} ({exact_rate:.1f}%)")
            lines.append(f"  Gap position accuracy: {gap_acc:.1f}%")
            lines.append(f"  Character accuracy: {char_acc:.1f}%")
            
            # Show worst mismatches
            mismatches = [c for c in comparisons if not c.exact_match]
            if mismatches:
                mismatches.sort(key=lambda x: x.character_accuracy)
                lines.append(f"  \n  Worst mismatches (top 5):")
                for c in mismatches[:5]:
                    lines.append(
                        f"    - {c.gene_name}: "
                        f"gap_acc={c.gap_position_accuracy*100:.1f}%, "
                        f"char_acc={c.character_accuracy*100:.1f}%, "
                        f"len_diff={c.actual_gapped_length - c.expected_gapped_length}"
                    )
    
    # Overall summary
    lines.append("\n" + "=" * 80)
    lines.append("OVERALL SUMMARY")
    lines.append("=" * 80)
    
    overall_exact_rate = overall_exact / overall_total * 100 if overall_total > 0 else 0
    overall_gap_acc = overall_gap_pos_matches / overall_gap_pos_total * 100 if overall_gap_pos_total > 0 else 100
    overall_char_acc = overall_char_matches / overall_char_total * 100 if overall_char_total > 0 else 100
    
    lines.append(f"\nTotal sequences validated: {overall_total}")
    lines.append(f"Exact matches: {overall_exact} ({overall_exact_rate:.1f}%)")
    lines.append(f"Gap position accuracy: {overall_gap_acc:.1f}%")
    lines.append(f"Character accuracy: {overall_char_acc:.1f}%")
    
    report = "\n".join(lines)
    print(report)
    
    if output_path:
        output_path.write_text(report)
        print(f"\nReport saved to: {output_path}")
    
    return report


def main():
    """Run gapping validation."""
    # Paths
    base_dir = Path(__file__).parent.parent
    custom_dir = base_dir / "sources" / "custom"
    template_dir = base_dir / "sources" / "imgt"
    
    print(f"Custom dir: {custom_dir}")
    print(f"Template dir: {template_dir}")
    
    # Find all species with custom data
    species_list = []
    for species_dir in custom_dir.iterdir():
        if species_dir.is_dir() and not species_dir.name.startswith(("_", ".", "raw")):
            # Check for gapped validation files
            has_gapped = any(species_dir.glob("*_gapped.fasta"))
            if has_gapped:
                species_list.append(species_dir.name)
    
    print(f"\nSpecies to validate: {species_list}")
    
    # Validate each species
    all_results = {}
    for species in species_list:
        print(f"\n{'='*60}")
        print(f"Validating {species}...")
        print(f"{'='*60}")
        
        results = validate_species_gapping(custom_dir, species, template_dir)
        if results:
            all_results[species] = results
    
    # Print report
    if all_results:
        output_path = base_dir / "tests" / "gapping_validation_report.txt"
        print_validation_report(all_results, output_path)


if __name__ == "__main__":
    main()
